/*
 * Originally generated by 'ng g ng-alain:plugin icon', then maintained by hand as the
 * scaffold's Chinese social logins (Alipay/Taobao/Weibo) were removed and the Persian/RTL
 * header widgets were added.
 *
 * Only icons this app actually renders are listed — `search`, `bars`, `down`, `loading` and
 * `close-circle` are omitted deliberately because `NzIconModule` registers them itself.
 *
 * `menu-fold` / `menu-unfold` are rendered by `@delon`'s own layout-default header trigger rather
 * than by a template in this repo, so the generator cannot find them.
 */

import {
  ArrowDownOutline,
  BorderLeftOutline,
  BorderRightOutline,
  CopyrightOutline,
  DashboardOutline,
  FieldNumberOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MobileOutline,
  SafetyCertificateOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  ArrowDownOutline,
  BorderLeftOutline,
  BorderRightOutline,
  CopyrightOutline,
  DashboardOutline,
  FieldNumberOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MobileOutline,
  SafetyCertificateOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
];
